#!/bin/zsh

# Exit as soon as an error is encountered
setopt ERR_EXIT

# [Finder]
# ========

# Disable any instance of "AnimateInfoPanes"
defaults write com.apple.finder DisableAllAnimations -bool true

# Don't display the full POSIX path to the selected file in the Finder window title
defaults write com.apple.finder _FXShowPosixPathInTitle -bool false

# Add a "Quit Finder" command to the Finder menu
defaults write com.apple.finder QuitMenuItem -bool true

# Automatically stop previews when scrolling
defaults write com.apple.finder AutoStopWhenScrollingOffBounds -bool true

# Automatically stop previews when selection changes
defaults write com.apple.finder AutoStopWhenSelectionChanges -bool true

# Automatically stop QuickLook when user switches active application
defaults write com.apple.finder QLHidePanelOnDeactivate -bool true

# Show the file-size column in search results
defaults write com.apple.finder SearchViewSettings.ListViewSettings.columns.size.visible -bool true

# Disable the warning when changing a file extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# Disable the warning when removing from iCloud
defaults write com.apple.finder FXEnableRemoveFromICloudDriveWarning -bool false

# Don't open new finder windows in the same tab
defaults write com.apple.finder FinderSpawnTab -bool false

# Show the path bar in Finder
defaults write com.apple.finder ShowPathbar -bool true

# Hide desktop icons completely
defaults write com.apple.finder CreateDesktop -bool false

# Disable the warning before emptying the Trash
defaults write com.apple.finder WarnOnEmptyTrash -bool false

# [Mail]
# ======

# Disable inline attachments (just show the icons)
defaults write com.appple.mail DisableInlineAttachmentViewing -bool true

# Prefer rich-text when drafting emails
defaults write com.apple.mail PreferPlainText -bool false

# Include original message in replies
defaults write com.apple.mail AlwaysIncludeOriginalMessage -bool true

# Don't automatically format the reply
defaults write com.apple.mail AutoReplyFormat -bool false

# Show most recent reply in email chain at the top
defaults write com.apple.mail ConversationViewSortDescending -bool true

# When opening an email chain, mark all messages as read
defaults write com.apple.mail ConversationViewMarkAllAsRead -bool true

# When searching for mail, don't include trash
defaults write com.apple.mail IndexTrash -bool false

# [Messages]
# ==========

# Disable automatic emoji substitution (i.e. use plain text smileys)
defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "automaticEmojiSubstitutionEnablediMessage" -bool false

# Disable smart quotes as it's annoying for messages that contain code
defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "automaticQuoteSubstitutionEnabled" -bool false

# Disable continuous spell checking
defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "continuousSpellCheckingEnabled" -bool false


# [Safari]
# ========

# Include the develop menu for Safari (inspect element, etc.)
defaults write com.apple.safari IncludeDevelopMenu -bool true

# Make Safari's search banners default to "Contains" rather than "Begins with"
defaults write com.apple.Safari FindOnPageMatchesWordStartsOnly -bool false

# [Terminal]
# ==========

# Only use UTF-8 in Terminal.app
defaults write -app Terminal StringEncodings -array 4

# [TextEdit]
# =========

# Use plain text mode for new TextEdit documents
defaults write -app TextEdit RichText -bool false

# [Photos]
# ========

# Prevent Photos from opening automatically when devices are plugged in
defaults write com.apple.imagecapture disableHotPlug -bool true

# [Keyboard]
# ==========

# Disable the accents that show up when doing a press-and-hold on a letter key
defaults write -g ApplePressAndHoldEnabled -bool false

# KeyRepeat, 1=15ms 2=30ms etc.
defaults write -g KeyRepeat -int 2

# [Autocorrect]
# =============

# Configure text substitutions
defaults write -g WebAutomaticTextReplacementEnabled -bool true
defaults write -g NSAutomaticSpellingCorrectionEnabled -bool false
defaults write -g NSAutomaticDashSubstitutionEnabled -bool false
defaults write -g NSAutomaticQuoteSubstitutionEnabled -bool false
defaults write com.apple.TextEdit SmartDashes -bool false

# [Clock]
# =======

# Disable the analog clock in the menu bar in favor of the digital clock
defaults write com.apple.menuextra.clock IsAnalog -bool false

# Set the clock in the menu bar
defaults write com.apple.menuextra.clock DateFormat -string 'EEE dd MMM h:mm:ss a'

# Enable blinking seperators in the menu bar's clock
defaults write com.apple.menuextra.clock FlashDateSeparators -bool true

# [Screenshots]
# =============

# Save screenshots in PNG format 
# (valid options are: HEIF, BMP, GIF, JPG, PNG, PDF, TIFF)
defaults write com.apple.screencapture 'type' -string 'heif'

# Change the default location screenshots are saved to
defaults write com.apple.screencapture 'location' -string "${HOME}/Desktop"

# When saving screencaptures, don't save timestamps
defaults write com.apple.screencapture 'include-date' -bool false

# When saving screencaptures, name the file "screenshot"
defaults write com.apple.screencapture 'name' -string 'screenshot'

# [Animations]
# ============

# Disable smooth scrolling
defaults write -g NSScrollAnimationEnabled -bool false

# Disable window animations
defaults write -g NSAutomaticWindowAnimationsEnabled -bool false

# Disable animations when opening a Quick Look window
defaults write -g QLPanelAnimationDuration -float 0

# Disable rubber band scrolling
defaults write -g NSScrollViewRubberbanding -bool false

# Disable animation while resizing windows before and after showing the version browser
defaults write -g NSDocumentRevisionsWindowTransformAnimation -bool false

# Disable the animation while showing a toolbar or menu bar in full screen 
defaults write -g NSToolbarFullScreenAnimationDuration -float 0

# Disable the animation while scrolling column views
defaults write -g NSBrowserColumnAnimationSpeedMultiplier -float 0

# Disable the animation while showing and hiding Mission Control, (command+numbers)
defaults write com.apple.dock expose-animation-duration -float 0

# Disable window resize animations
defaults write -g NSWindowResizeTime -float 0.001

# Don't automatically hide the menu bar
defaults write -g _HIHideMenuBar -bool false

# Launchpad
# ---------

# Showing the Launchpad
defaults write com.apple.dock springboard-show-duration -float 0
# Hiding the Launchpad
defaults write com.apple.dock springboard-hide-duration -float 0
# Moving between pages
defaults write com.apple.dock springboard-page-duration -float 0

# Dock
# ----

# Disable animation for hiding the dock
defaults write com.apple.dock autohide-time-modifier -float 0

# Hide the dock immediately after it is not in use
defaults write com.apple.dock autohide-delay -float 0

# Mail
# ----
# Disable animation for replying to mail
defaults write com.apple.mail DisableReplyAnimations -bool true

# Disable animation for sending mail
defaults write com.apple.mail DisableSendAnimations -bool true

# Safari
# ------

# Disable the delay when rendering a web page
defaults write com.apple.safari WebKitInitialTimedLayoutDelay -float 0.1


###############################################################################
# Trackpad
###############################################################################

# Disable "natural" scrolling
#defaults write -g com.apple.swipescrolldirection -bool false

# Tap to click for this user and for the login screen
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults -currentHost write -g com.apple.mouse.tapBehavior -int 1
defaults write -g com.apple.mouse.tapBehavior -int 1

# Swipe between pages with three fingers
#defaults write -g AppleEnableSwipeNavigateWithScrolls -bool true
#defaults -currentHost write -g com.apple.trackpad.threeFingerHorizSwipeGesture -int 1
#defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadThreeFingerHorizSwipeGesture -int 1

# Force Click and haptic feedback
defaults write -g com.apple.trackpad.forceClick -bool true
defaults write com.apple.AppleMultitouchTrackpad ForceSuppressed -bool false
defaults write com.apple.AppleMultitouchTrackpad ActuateDetents -bool true

# Silent clicking
defaults write com.apple.AppleMultitouchTrackpad ActuationStrength -int 0

# Haptic feedback
# 0: Light
# 1: Medium
# 2: Firm
defaults write com.apple.AppleMultitouchTrackpad FirstClickThreshold -int 0
defaults write com.apple.AppleMultitouchTrackpad SecondClickThreshold -int 0

# Tracking speed (0=Slow 3=Fast)
defaults write NSGlobalDomain com.apple.trackpad.scaling -float 5

# [Misc]
# ======

defaults write -g AppleLocale 'en_US@calendar=iso8601'

# Change the date format from US's "1/1/70" to ISO 8601's "1970-01-01"
defaults write -g AppleICUDateFormatStrings -dict 1 'y-MM-dd'

# Change the time format to use more descriptive timezones
defaults write -g AppleICUTimeFormatStrings -dict \
	1 'hh:mm a' \
	2 'hh:mm:ss a' \
	3 'HH:mm:ssZZZZZ' \
	4 'hh:mm:ssZZZZZ (VV)'

# Make sure weeks still start on Sunday (ISO 8601 violation)
defaults write -g AppleFirstWeekday -dict 'iso8601' 1

# Configure the two languages, English and Chinese
defaults write -g AppleLanguages -array 'en-US' 'zh-Hans-US'

defaults write -g NSUserQuotesArray -array \" \" \' \'

# Prevent Spotlight search from indexing all external volumes (including network volumes)
sudo defaults write /Library/Preferences/com.apple.SpotlightServer.plist ExternalVolumesIgnore -bool true

# Automatically expand "Save As..." dialogue boxes
defaults write -g NSNavPanelExpandedStateForSaveMode -bool true
defaults write -g NSNavPanelExpandedStateForSaveMode2 -bool true

# Enable automatic back-up to time machine
defaults write com.apple.TimeMachine AutoBackup -bool true

# Show all filename extensions (e.g. example.txt)
defaults write -g AppleShowAllExtensions -bool true

# Enable AirDrop over ethernet
defaults write com.apple.NetworkBrowser BrowseAllInterfaces -bool true

# Enable preview thumbnails for videos
defaults write com.apple.QuickLookDaemon QLDisableQTThumbnails -bool true

# Automatically quit printer app once the print jobs complete
defaults write com.apple.print.PrintingPrefs 'Quit When Finished' -bool true

# Disable the "Are you sure you want to open this application?" dialog
defaults write com.apple.LaunchServices LSQuarantine -bool false

# Enable font smoothing to improve quality of text on screen
defaults write -g CGFontRenderingFontSmoothingDisabled -bool false

# Enable the power chime when computer is plugged into charger
defaults write com.apple.PowerChime ChimeOnAllHardware -bool true

# Prioritize being reachable over the network, even at the cost of less sleep
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.PowerManagement PrioritizeNetworkReachabilityOverSleep -bool true

# Allow SMB file transfers from anywhere
sudo defaults write /Library/Preferences/com.apple.NetworkAuthorization AllowUnknownServers -bool true

# Allow remote AppleEvents to target apps in any user session
defaults write /Library/Preferences/com.apple.AEServer RestrictAccessToUserSession -bool false

# Don't write DS_Store
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# Treat the help window (the one that shows user manuals) 
# as a normal window link to source
defaults write com.apple.helpviewer DevMode -bool true

# Check for software updates daily, not just once per week
defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1

# Expand save panel by default
defaults write -g NSNavPanelExpandedStateForSaveMode -bool true
defaults write -g NSNavPanelExpandedStateForSaveMode2 -bool true

# Expand print panel by default
defaults write -g PMPrintingExpandedStateForPrint -bool true
defaults write -g PMPrintingExpandedStateForPrint2 -bool true

# Save to disk (not to iCloud) by default
defaults write -g NSDocumentSaveNewDocumentsToCloud -bool false

# Maximize a window by double clicking on navigation bar
defaults write -g AppleActionOnDoubleClick -string 'Maximize'

# Disable messages from Microsoft Auto Update without removing it entirely
defaults write com.microsoft.autoupdate2.plist \
    AcknowledgedDataCollectionPolicy RequiredDataOnly

# Restart the applications that were modified
killall \
	'Activity Monitor' 'Address Book' 'Calendar' 'Contacts' \
	'Dock' 'Finder' 'Mail' 'Messages' 'Photos' 'Safari' \
	'SystemUIServer' 'Terminal'

# When performing a search, search the current folder by default
# defaults write com.apple.finder FXDefaultSearchScope -string 'SCcf'


# # Use the Cloudflare DNS Service
# networksetup -setdnsservers Wi-Fi \
# 	1.1.1.1 \
# 	1.0.0.1 \
# 	2606:4700:4700::1111 \
# 	2606:4700:4700::1001
#
# # Cancel sound effects for the UI
# defaults write com.apple.systemsound "com.apple.sound.uiaudio.enabled" -bool false

# # Copy the San Francisco Monospace font to the FontBook
# sudo cp -v /System/Applications/Utilities/Terminal.app/Contents/Resources/Fonts/*otf /Library/Fonts/

# Disable key-repeat
# defaults write -g InitialKeyRepeat -int 0
# bug, alters the behavior of cmd-tab

# Hide the status bar in Finder
# defaults write com.apple.finder ShowStatusBar -bool false

# defaults write com.apple.safari UserStyleSheetEnabled -bool true
# defaults write com.apple.safari UserStyleSheetLocationURLString -string $XDG_CONFIG_HOME/css/safari.css

# Enable text selection in quick look windows (Discontinued, no longer works)
# defaults write com.apple.finder QLEnableTextSelection -bool true


