.\" For help, read groff_man(7)
.\" ==============================================================================
.\" .TH: "Title Heading"
.\" .TH title section [footer-middle] [footer-outside] [header-middle]
.\" .TH GROFF    1       "Version"        "Date"         "Subtitle"
.TH COMMAND 1 "0.0.1" "2021-01-01" "Putting the man in command"
.\" ==============================================================================
.\" .SH: "Section Heading"
.\" .SH [heading-text]
.SH NAME
.\" The name of the function, program or utility followed by 
.\" a one-line description of its purpose. 
.B git 
\- version control for error prone programmers
.\" ==============================================================================
.SH SYNOPSIS
.
.\" Insert the general syntax used to invoke the command
.SY "command \-f"
.RI [ FILE
\&.\|.\|.\&]
.RI [ ARGS
\&.\|.\|.\&]
.
.SY "command \-i FILE"
.RI [ ARGS
\&.\|.\|.\&]
.
.YS
.
.\" ==============================================================================
.SH DESCRIPTION
.
.\" Insert a detailed description of the function, program or utility
The
.I man
macro package for
.I groff
is used to produce manual pages
.\" We use an unbreakable space \~ here to keep the phrase intact for
.\" its introduction; in subsequent discussion, that is not important.
(\(lqman\~pages\(rq)
like the one you are reading.
.
.\" ==============================================================================
.SH OPTIONS
.
.\" List all options and their description
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Display help message and exit\&.
.\" ==============================================================================
.SH AUTHOR
This manual was written by
.\" .MT austintraver@users.noreply.github.com 
.\" Austin Traver 
.\" .ME
.UR https://github.com/austintraver
@austintraver
.UE
who in all likelihood was doing this to avoid working on a project that was both \
 more urgent and more important
.
.\" ==============================================================================
.SH SEE ALSO
.IR other (5), 
.IR man (7), 
.IR pages (1)
.
.\" ==============================================================================
