name = "Austin Traver"
downloads-dir = "~/Downloads"
signature = "Best,\nAustin"

[gmail]
default = true
email = "austintraver@gmail.com"

imap-host = "imap.gmail.com"
imap-port = 993
imap-login = "austintraver@gmail.com"
imap-passwd-cmd = "security find-generic-password -s himalaya -a austintraver@gmail.com -w"

smtp-host = "smtp.gmail.com"
smtp-port = 465
smtp-login = "austintraver@gmail.com"
smtp-passwd-cmd = "security find-generic-password -s himalaya -a austintraver@gmail.com -w"

[icloud]
default = true
email = "austintraver@icloud.com"

imap-host = "imap.mail.me.com"
imap-port = 993
imap-login = "austintraver@icloud.com"
imap-passwd-cmd = "security find-generic-password -s himalaya -a austintraver@icloud.com -w"

smtp-host = "smtp.mail.me.com"
smtp-port = 587
smtp-login = "austintraver@icloud.com"
smtp-passwd-cmd = "security find-generic-password -s himalaya -a austintraver@icloud.com -w"
